### ISSUE TITLE
Assigning Left and Right Ctrl/Shift/Alt Separately

### ISSUE THREAD

**Issue by Agetian** [MrHuu/dosbox-3ds#3]
I tried playing Pinball Fantasies on DosBox-3DS, and it played perfectly fine in lo-res mode. However, I had difficulty setting up the controls because the game uses Left and Right Shift/Ctrl/Alt keys separately to control the left and the right flipper, respectively. The integrated keyboard only has one of each, which seems to map to the Right counterpart, and I didn't find any obvious, visible and intuitive way to specify Left Ctrl/Left Shift/Left Alt separate from the Right one. Therefore, I had to figure out the scancode for the needed keys from the source and then manually hex-edit the mapper file in order to assign the Left Shift to L and the Right Shift to R, which made the game perfectly playable (the emulator itself is perfectly capable of using both Shift keys individually, it's just that the mapper interface seems to be missing the ability to specify it or I'm missing something obvious, perhaps, and don't see it :) ).

All that said, thanks for the wonderful 3DS build, this works great with many older DOS titles.

**Comment by MrHuu** [comment]
Currently, the controller mappings allow these keys to be pressed:
https://github.com/MrHuu/dosbox-3ds/blob/a6f44ac1c6e73afb899641117906e469a4c43f2b/src/platform/ctr/ctr_keyboard.h#L8-L29

But not all of these keys are available on the bottom screen keyboard as you've noticed.
I think only the 'left' modifier keys still need to be added.

They could probably be added on the 'symbols' keyboard, leaving the 'character' keyboard with their 'right' counterparts as is.

Since the modifier keys on the bottom screen keyboard are handled separately, with right* keys hardcoded, it requires some other changes as well. Which needed to be done anyway, so i'll keep this in mind when working on it.

**Comment by MrHuu** [comment]
Latest build is capable of mapping left or right modifier keys.

I'll close this for now, feel free to open a new issue if desired.
